crudapp/urls.py
from django.contrib import admin
from django.urls import path
from crudapp import views
app_name = 'crud'
urlpatterns = [
    path('', views.read, name='read' ),
    path('add/', views.userdetail, name='add'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

crudproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudapp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

 

crudapp/models.py
from django.db import models

# Create your models here.
class Userdetail(models.Model):
    firstname = models.CharField(max_length=25)
    lastname = models.CharField(max_length=25)
    

crudapp/forms.py
from django import forms
from crudapp.models import Userdetail

class Userdetails_form(forms.ModelForm):
    class Meta:
        model = Userdetail
        fields = ('__all__')

crudapp/views.py
from django.shortcuts import render, redirect
from crudapp.forms import Userdetails_form
from .models import Userdetail
from django.http import HttpResponse

# Create your views here.
def userdetail(request):
    if request.method == "POST":
        form = Userdetails_form(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()

                return redirect('crud:read')

            except:
                return HttpResponse('failure')

        else:
            return HttpResponse(form.errors)

    else:
        return render(request, 'index.html')

def read(request):
    users = Userdetail.objects.all()
    return render(request, 'views.html',{'users':users})


def update(request, id):
    users = Userdetail.objects.get(id=id)
    if request.method == "POST":
        form = Userdetails_form(request.POST, instance=users)
        if form.is_valid():
            try:
                form.save()
                return redirect('crud:read')
            except:
                return HttpResponse('failure')

        else:
            return HttpResponse(form.errors)    
    else:
        return render(request, 'update.html',{'users':users})

def delete(request, id):
    users = Userdetail.objects.get(id=id)
    users.delete()
    return redirect('crud:read')
 

crudapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method=post>
        {% csrf_token %}
        First name:<br>
  <input type="text" name="firstname"><br>
  Last name:<br>
  <input type="text" name="lastname">
   <input type = "submit">     
    </form>
</body>
</html>

crudapp/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method=post action="{% url 'crud:update' users.id %}">
        {% csrf_token %}
        First name:<br>
  <input type="text" name="firstname" value="{{users.firstname}}"><br>
  Last name:<br>
  <input type="text" name="lastname" value="{{users.lastname}}">
   <input type = "submit">     
    </form>
</body>
</html>

crudapp/templates/views.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="{% static 'css/main.css'%}" rel="stylesheet"/>
    <link href="{% static 'style.css' %}" rel="stylesheet"/>
</head>
<body>
    <h1>User list</h1>
    <table>
        <tr>
            <th>S.N</th>
            <th>Firstname</th>
            <th>Lastname</th>
        </tr>
    {% for user in users %}
    <tr>
        <td>{{ forloop.counter}}</td>   
        <td>{{user.firstname}}</td>
        <td>{{user.lastname}}</td>
        <td><a href="{% url 'crud:update' user.id %}"><button>Update</button></a></td>
        <td><a href="{% url 'crud:delete' user.id %}"><button>Delete</button></a></td>

    </tr>   
    {%endfor%}
    
    </table>
    <a href="{% url 'crud:add' %}" ><button>Add</button></a>
    <p id="demo"></p>
    <script src="{% static 'js/main.js'%}"></script>
</body>
</html>